name: "custom-action"
description: "my first custom action"

inputs:
  firstGreeting:
    description:  "Who would you like to greet in the console"
    required: true
    default:  "Mahdi"
  pathOfGreating:
    description:  "path for greating"
    required: true
    default:  ".github/actions/hello-world/default"
  secondGreeting:
    description:  "another person to greet"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
