name: "my hello action"

description: "say hello with GitHub Actions"

inputs:
  firstGreeting:
    description: "who would you like to greet in the console"
    required: true
    default: "Mahdi"

  pathOfGreeting:
    description: "path to greet"
    required: true
    default: ".github/action/hello-world"

  thirdGreeting:
    description: "a third greeting"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
